server:
  port: 8088
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myweb?serverTimezone=UTC
    username: root
    password: 123456
    druid:
      filter:
        stat:
          log-slow-sql: true
  #文件上传
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
#      redis
  data:
    redis:
      host: 192.168.10.101
      port: 6379
      lettuce:
        pool:
          max-active: 8
          max-wait: 100
          min-idle: 0
          max-idle: 8


  freemarker:
    cache: false #关闭模板缓存，方便测试
    settings:
      template_update_delay: 0 #检查模板更新延迟时间，设置0会立即检查
    suffix: .ftl  #指定Freemarker模板文件的后缀名


#开启数据库与实体类驼峰命名与下划线命名的转换
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl




